Add checksum insertion and offloading
stm32-rs/stm32-eth pull request #48
Opened 2022-06-24 22:20 UTC by dsgruss

The stm32 has a built-in module to automatically handle checksums inside IP headers and TCP, UDP, and ICMP payloads, on both the transmit and receive paths. For reference, the [stm4 manual](https://www.st.com/resource/en/reference_manual/rm0090-stm32f405415-stm32f407417-stm32f427437-and-stm32f429439-advanced-armbased-32bit-mcus-stmicroelectronics.pdf) covers transmitting on pages 1141 and 1172, and receiving on pages 1145 and 1184.

For transmission, this involves setting two CIC bits in the transmit descriptor so that checksums are calculated and inserted. On the receive side, we set a bit in the maccr register, and the error is grouped into the general error summary flag on the receive descriptor.

In my (very rough) profiling, this change resulted in about a 30% speedup at 75 Mbps Tx over doing the checksums in software inside smoltpc.

Looking through some other manuals, this feature appears to be supported in all MCUs that have a hardware ETH controller. For example:

- [stmf1 manual](https://www.st.com/resource/en/reference_manual/rm0008-stm32f101xx-stm32f102xx-stm32f103xx-stm32f105xx-and-stm32f107xx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf), pages 987, 1019, etc.
- [stmf7 manual](https://www.st.com/resource/en/reference_manual/rm0410-stm32f76xxx-and-stm32f77xxx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf), pages 1784, 1816, etc.

Let me know if this would be better done some other way, such as config setting, feature, ...

2022-07-02 12:40 UTC, datdenkikniet commented
I think this sounds like a good addition, and it would make sense to enable unconditionally given that it appears that all parts support this feature, and it almost exclusively comes with upsides.

All appropriate bits seem to be set: 
* `cic0` and `cic1`, and `tsf` for TX checksum offloading  
* `ipco` for RX ipv4 checksum offloading

The CI seems to agree with your observation about it being supported on all parts, so that's very nice too.

@korken89 @thalesfragoso would appreciate another look

Left a small request for a little extra documentation

2022-07-02 12:45 UTC, datdenkikniet commented
Correction: I thought we had already enabled enhanced descriptors (`edfe` in `ETHDMABMR`), but it seems like I have made a mistake there. On `stm32f4xx` (and most likely `stm32f7xx` parts), enhanced descriptors _must_ be enabled for offload support. See page 1186 of the f4 RM.

2022-07-02 12:46 UTC, datdenkikniet requested changes

2022-07-02 12:46 UTC, datdenkikniet commented on src/lib.rs
> +            .ipco()
For IPv4 checksum offload support, Enhanced Descriptors must be enabled on `f4` and `f7` parts (`f1` parts don't seem to have this requirement, nor support for enhanced descriptors).

2022-07-07 04:14 UTC, dsgruss commented
Interesting! I had missed that part of the manual. I'm on an `stm32f429` and, as far as I could tell, packets with malformed headers were still dropped even without enabling enhanced descriptors and correct packet data came through unaltered...

Is it alright to set the descriptor width to 8 words even on the `f1` parts, or should there be a config check there as well?

2022-07-08 08:47 UTC, datdenkikniet commented
Aha, that's interesting indeed! Wonder how that works...

Hmm, I'm not sure. We're running the descriptors in "chain" mode (aka singly-linked-list mode), so it _should_ be fine since the descriptors will point to the next entry by address. However, I don't have access to an f1 so have no way to test it.

I think it'd be best if we avoid using 8-word wide descriptors on f1 for now. Luckily, it's quite easy:

```rust
#[cfg(not(feature = "stm32f107"))]
const DESC_SIZE: usize = 8;

#[cfg(feature = "stm32f107")]
const DESC_SIZE: usize = 4;

#[repr(C)]
pub struct Descriptor {
    desc: Aligned<A8, [u32; DESC_SIZE]>,
}

...
impl Descriptor {
    pub const fn new() -> Self {
        Self {
            desc: Aligned([0; DESC_SIZE]),
        }
    }
...
}

```

2022-07-09 11:32 UTC, datdenkikniet commented
LGTM!

2022-07-09 11:32 UTC, datdenkikniet approved these changes

2022-07-09 11:32 UTC, merged